'use strict';

var vendors = {
  "0033": "Paradyne Corp.",
  "003D": "master",
  "0070": "Hauppauge Computer Works Inc.",
  "0100": "USBPDO-8",
  "0123": "General Dynamics",
  "0315": "SK - Electronics Co., Ltd.",
  "0402": "Acer aspire one",
  "046D": "Logitech Inc.",
  "0483": "UPEK",
  "04A9": "Canon",
  "04B3": "IBM",
  "04D9": "Filco",
  "04F2": "Chicony Electronics Co.",
  "051D": "ACPI\VEN_INT&DEV_33A0",
  "0529": "Aladdin E-Token",
  "0553": "Aiptek USA",
  "158F": "Alcor Micro Corp.",
  "0590": "Omron Corp",
  "05AC": "Apple Inc.",
  "05E1": "D-MAX",
  "064E": "SUYIN Corporation",
  "067B": "Prolific Technology Inc.",
  "06FE": "Acresso Software Inc.",
  "0711": "SIIG, Inc.",
  "093A": "KYE Systems Corp. / Pixart Imaging",
  "096E": "USB Rockey dongle from Feitain",
  "0A5C": "Broadcom Corporation",
  "0A89": "BREA Technologies Inc.",
  "0A92": "Egosys, Inc.",
  "0AC8": "ASUS",
  "0B05": "Toshiba Bluetooth RFBUS, RFCOM, RFHID",
  "0C45": "Microdia Ltd.",
  "0CF3": "TP-Link",
  "0D2E": "Feedback Instruments Ltd.",
  "0D8C": "C-Media Electronics, Inc.",
  "0DF6": "Sitecom",
  "0E11": "Compaq Computer Corp.",
  "0E8D": "MediaTek Inc.",
  "1000": "LSI Logic",
  "1001": "Kolter Electronic - Germany",
  "1002": "Advanced Micro Devices, Inc.",
  "1003": "ULSI",
  "1004": "VLSI Technology",
  "1006": "Reply Group",
  "1007": "Netframe Systems Inc.",
  "1008": "Epson",
  "100A": "Ã‚as Ltd. de Phoenix del Âƒ de TecnologÃƒ",
  "100B": "National Semiconductors",
  "100C": "Tseng Labs",
  "100D": "AST Research",
  "100E": "Weitek",
  "1010": "Video Logic Ltd.",
  "1011": "Digital Equipment Corporation",
  "1012": "Micronics Computers Inc.",
  "1013": "Cirrus Logic",
  "1014": "International Business Machines Corp.",
  "1016": "Fujitsu ICL Computers",
  "1017": "Spea Software AG",
  "1018": "Unisys Systems",
  "1019": "Elitegroup Computer System",
  "101A": "NCR Corporation",
  "101B": "Vitesse Semiconductor",
  "101E": "American Megatrends Inc.",
  "101F": "PictureTel Corp.",
  "1020": "Hitachi Computer Electronics",
  "1021": "Oki Electric Industry",
  "1022": "Advanced Micro Devices",
  "1023": "TRIDENT MICRO",
  "1025": "Acer Incorporated",
  "1028": "Dell Inc.",
  "102A": "LSI Logic Headland Division",
  "102B": "Matrox Electronic Systems Ltd.",
  "102C": "Asiliant (Chips And Technologies)",
  "102D": "Wyse Technology",
  "102E": "Olivetti Advanced Technology",
  "102F": "Toshiba America",
  "1030": "TMC Research",
  "1031": "miro Computer Products AG",
  "1033": "NEC Electronics",
  "1034": "Burndy Corporation",
  "1036": "Future Domain",
  "1037": "Hitachi Micro Systems Inc",
  "1038": "AMP Incorporated",
  "1039": "Silicon Integrated Systems",
  "103A": "Seiko Epson Corporation",
  "103B": "Tatung Corp. Of America",
  "103C": "Hewlett-Packard",
  "103E": "Solliday Engineering",
  "103F": "Logic Modeling",
  "1041": "Computrend",
  "1043": "Asustek Computer Inc.",
  "1044": "Distributed Processing Tech",
  "1045": "OPTi Inc.",
  "1046": "IPC Corporation LTD",
  "1047": "Genoa Systems Corp.",
  "1048": "ELSA GmbH",
  "1049": "Fountain Technology",
  "104A": "STMicroelectronics",
  "104B": "Mylex / Buslogic",
  "104C": "Texas Instruments",
  "104D": "Sony Corporation",
  "104E": "Oak Technology",
  "104F": "Co-Time Computer Ltd.",
  "1050": "Winbond Electronics Corp.",
  "1051": "Anigma Corp.",
  "1053": "Young Micro Systems",
  "1054": "Hitachi Ltd",
  "1055": "Standard Microsystems Corp.",
  "1056": "ICL",
  "1057": "Motorola",
  "1058": "Electronics & Telecommunication Res",
  "1059": "Kontron Canada",
  "105A": "Promise Technology",
  "105B": "Mobham chip",
  "105C": "Wipro Infotech Limited",
  "105D": "Number Nine Visual Technology",
  "105E": "Vtech Engineering Canada Ltd.",
  "105F": "Infotronic America Inc.",
  "1060": "United Microelectronics",
  "1061": "8x8 Inc.",
  "1062": "Maspar Computer Corp.",
  "1063": "Ocean Office Automation",
  "1064": "Alcatel Cit",
  "1065": "Texas Microsystems",
  "1066": "Picopower Technology",
  "1067": "Mitsubishi Electronics",
  "1068": "Diversified Technology",
  "106A": "Aten Research Inc.",
  "106B": "Apple Inc.",
  "106C": "Hyundai Electronics America",
  "106D": "Sequent Computer Systems",
  "106E": "DFI Inc.",
  "106F": "City Gate Development LTD",
  "1070": "Daewoo Telecom Ltd.",
  "1071": "Mitac",
  "1072": "GIT Co. Ltd.",
  "1073": "Yamaha Corporation",
  "1074": "Nexgen Microsystems",
  "1075": "Advanced Integration Research",
  "1077": "QLogic Corporation",
  "1078": "Cyrix Corporation",
  "1079": "I-Bus",
  "107A": "Networth controls",
  "107B": "Gateway 2000",
  "107C": "Goldstar Co. Ltd.",
  "107D": "Leadtek Research",
  "107E": "Testernec",
  "107F": "Data Technology Corporation",
  "1080": "Cypress Semiconductor",
  "1081": "Radius Inc.",
  "1082": "EFA Corporation Of America",
  "1083": "Forex Computer Corporation",
  "1084": "Parador",
  "1085": "Tulip Computers Intl BV",
  "1086": "J. Bond Computer Systems",
  "1087": "Cache Computer",
  "1088": "Microcomputer Systems (M) Son",
  "1089": "Data General Corporation",
  "108A": "SBS Operations",
  "108C": "Oakleigh Systems Inc.",
  "108D": "Olicom",
  "108E": "Sun Microsystems",
  "108F": "Systemsoft Corporation",
  "1090": "Encore Computer Corporation",
  "1091": "Intergraph Corporation",
  "1092": "Diamond Computer Systems",
  "1093": "National Instruments",
  "1094": "Apostolos",
  "1095": "Silicon Image, Inc.",
  "1096": "Alacron",
  "1097": "Appian Graphics",
  "1098": "Quantum Designs Ltd.",
  "1099": "Samsung Electronics Co. Ltd.",
  "109A": "Packard Bell",
  "109B": "Gemlight Computer Ltd.",
  "109C": "Megachips Corporation",
  "109D": "Zida Technologies Ltd.",
  "109E": "Brooktree Corporation",
  "109F": "Trigem Computer Inc.",
  "10A0": "Meidensha Corporation",
  "10A1": "Juko Electronics Inc. Ltd.",
  "10A2": "Quantum Corporation",
  "10A3": "Everex Systems Inc.",
  "10A4": "Globe Manufacturing Sales",
  "10A5": "Racal Interlan",
  "10A8": "Sierra Semiconductor",
  "10A9": "Silicon Graphics",
  "10AB": "Digicom",
  "10AC": "Honeywell IASD",
  "10AD": "Winbond Systems Labs",
  "10AE": "Cornerstone Technology",
  "10AF": "Micro Computer Systems Inc.",
  "10B0": "Gainward GmbH",
  "10B1": "Cabletron Systems Inc.",
  "10B2": "Raytheon Company",
  "10B3": "Databook Inc.",
  "10B4": "STB Systems",
  "10B5": "PLX Technology Inc.",
  "10B6": "Madge Networks",
  "10B7": "3Com Corporation",
  "10B8": "Standard Microsystems Corporation",
  "10B9": "Ali Corporation",
  "10BA": "Mitsubishi Electronics Corp.",
  "10BB": "Dapha Electronics Corporation",
  "10BC": "Advanced Logic Research Inc.",
  "10BD": "Surecom Technology",
  "10BE": "Tsenglabs International Corp.",
  "10BF": "MOST Corp.",
  "10C0": "Boca Research Inc.",
  "10C1": "ICM Corp. Ltd.",
  "10C2": "Auspex Systems Inc.",
  "10C3": "Samsung Semiconductors",
  "10C4": "Award Software Intl Inc.",
  "10C5": "Xerox Corporation",
  "10C6": "Rambus Inc.",
  "10C8": "Neomagic Corporation",
  "10C9": "Dataexpert Corporation",
  "10CA": "Fujitsu Siemens",
  "10CB": "Omron Corporation",
  "10CD": "Advanced System Products",
  "10CF": "Fujitsu Ltd.",
  "10D1": "Future+ Systems",
  "10D2": "Molex Incorporated",
  "10D3": "Jabil Circuit Inc.",
  "10D4": "Hualon Microelectronics",
  "10D5": "Autologic Inc.",
  "10D6": "Wilson .co .ltd",
  "10D7": "BCM Advanced Research",
  "10D8": "Advanced Peripherals Labs",
  "10D9": "Macronix International Co. Ltd.",
  "10DB": "Rohm Research",
  "10DC": "CERN-European Lab. for Particle Physics",
  "10DD": "Evans & Sutherland",
  "10DE": "NVIDIA",
  "10DF": "Emulex Corporation",
  "10E1": "Tekram Technology Corp. Ltd.",
  "10E2": "Aptix Corporation",
  "10E3": "Tundra Semiconductor Corp.",
  "10E4": "Tandem Computers",
  "10E5": "Micro Industries Corporation",
  "10E6": "Gainbery Computer Products Inc.",
  "10E7": "Vadem",
  "10E8": "Applied Micro Circuits Corp.",
  "10E9": "Alps Electronic Corp. Ltd.",
  "10EA": "Tvia, Inc.",
  "10EB": "Artist Graphics",
  "10EC": "Realtek Semiconductor Corp.",
  "10ED": "Ascii Corporation",
  "10EE": "Xilinx Corporation",
  "10EF": "Racore Computer Products",
  "10F0": "Curtiss-Wright Controls Embedded Computing",
  "10F1": "Tyan Computer",
  "10F2": "Achme Computer Inc. - GONE !!!!",
  "10F3": "Alaris Inc.",
  "10F4": "S-Mos Systems",
  "10F5": "NKK Corporation",
  "10F6": "Creative Electronic Systems SA",
  "10F7": "Matsushita Electric Industrial Corp.",
  "10F8": "Altos India Ltd.",
  "10F9": "PC Direct",
  "10FA": "Truevision",
  "10FB": "Thesys Microelectronics",
  "10FC": "I-O Data Device Inc.",
  "10FD": "Soyo Technology Corp. Ltd.",
  "10FE": "Fast Electronic GmbH",
  "10FF": "Ncube",
  "1100": "Jazz Multimedia",
  "1101": "Initio Corporation",
  "1102": "Creative Technology LTD.",
  "1103": "HighPoint Technologies, Inc.",
  "1104": "Rasterops",
  "1105": "Sigma Designs Inc.",
  "1106": "VIA Technologies, Inc.",
  "1107": "Stratus Computer",
  "1108": "Proteon Inc.",
  "1109": "Adaptec/Cogent Data Technologies",
  "110A": "Siemens AG",
  "110B": "Chromatic Research Inc",
  "110C": "Mini-Max Technology Inc.",
  "110D": "ZNYX Corporation",
  "110E": "CPU Technology",
  "110F": "Ross Technology",
  "1112": "Osicom Technologies Inc.",
  "1113": "Accton Technology Corporation",
  "1114": "Atmel Corp.",
  "1116": "Data Translation, Inc.",
  "1117": "Datacube Inc.",
  "1118": "Berg Electronics",
  "1119": "ICP vortex Computersysteme GmbH",
  "111A": "Efficent Networks",
  "111C": "Tricord Systems Inc.",
  "111D": "Integrated Device Technology Inc.",
  "111F": "Precision Digital Images",
  "1120": "EMC Corp.",
  "1121": "Zilog",
  "1123": "Excellent Design Inc.",
  "1124": "Leutron Vision AG",
  "1125": "Eurocore/Vigra",
  "1127": "FORE Systems",
  "1129": "Firmworks",
  "112A": "Hermes Electronics Co. Ltd.",
  "112C": "Zenith Data Systems",
  "112D": "Ravicad",
  "112E": "Infomedia",
  "1130": "Computervision",
  "1131": "NXP Semiconductors N.V.",
  "1132": "Mitel Corp.",
  "1133": "Eicon Networks Corporation",
  "1134": "Mercury Computer Systems Inc.",
  "1135": "Fuji Xerox Co Ltd",
  "1136": "Momentum Data Systems",
  "1137": "Cisco Systems Inc",
  "1138": "Ziatech Corporation",
  "1139": "Dynamic Pictures Inc",
  "113A": "FWB Inc",
  "113B": "Network Computing Devices",
  "113C": "Cyclone Microsystems Inc.",
  "113D": "Leading Edge Products Inc",
  "113E": "Sanyo Electric Co",
  "113F": "Equinox Systems",
  "1140": "Intervoice Inc",
  "1141": "Crest Microsystem Inc",
  "1142": "Alliance Semiconductor",
  "1143": "Netpower Inc",
  "1144": "Cincinnati Milacron",
  "1145": "Workbit Corp",
  "1146": "Force Computers",
  "1147": "Interface Corp",
  "1148": "Marvell Semiconductor Germany GmbH",
  "1149": "Win System Corporation",
  "114A": "VMIC",
  "114B": "Canopus corporation",
  "114C": "Annabooks",
  "114D": "IC Corporation",
  "114E": "Nikon Systems Inc",
  "114F": "Digi International",
  "1150": "Thinking Machines Corporation",
  "1151": "JAE Electronics Inc.",
  "1153": "Land Win Electronic Corp",
  "1154": "Melco Inc",
  "1155": "Pine Technology Ltd",
  "1156": "Periscope Engineering",
  "1157": "Avsys Corporation",
  "1158": "Voarx R&D Inc",
  "1159": "Mutech",
  "115A": "Harlequin Ltd",
  "115B": "Parallax Graphics",
  "115C": "Photron Ltd.",
  "115D": "Xircom",
  "115E": "Peer Protocols Inc",
  "115F": "Maxtor Corporation",
  "1160": "Megasoft Inc",
  "1161": "PFU Ltd",
  "1162": "OA Laboratory Co Ltd",
  "1163": "mohamed alsherif",
  "1164": "Advanced Peripherals Tech",
  "1165": "Imagraph Corporation",
  "1166": "Broadcom / ServerWorks",
  "1167": "Mutoh Industries Inc",
  "1168": "Thine Electronics Inc",
  "1169": "Centre f/Dev. of Adv. Computing",
  "116A": "Luminex Software, Inc",
  "116B": "Connectware Inc",
  "116C": "Intelligent Resources",
  "116E": "Electronics for Imaging",
  "1170": "Inventec Corporation",
  "1172": "Altera Corporation",
  "1173": "Adobe Systems",
  "1174": "Bridgeport Machines",
  "1175": "Mitron Computer Inc.",
  "1176": "SBE",
  "1177": "Silicon Engineering",
  "1178": "Alfa Inc",
  "1179": "Toshiba corporation",
  "117A": "A-Trend Technology",
  "117B": "LG (Lucky Goldstar) Electronics Inc.",
  "117C": "Atto Technology",
  "117D": "Becton & Dickinson",
  "117E": "T/R Systems",
  "117F": "Integrated Circuit Systems",
  "1180": "RicohCompany,Ltd.",
  "1183": "Fujikura Ltd",
  "1184": "Forks Inc",
  "1185": "Dataworld",
  "1186": "D-Link System Inc",
  "1187": "Philips Healthcare",
  "1188": "Shima Seiki Manufacturing Ltd.",
  "1189": "Matsushita Electronics",
  "118A": "Hilevel Technology",
  "118B": "Hypertec Pty Ltd",
  "118C": "Corollary Inc",
  "118D": "BitFlow Inc",
  "118E": "Hermstedt AG",
  "118F": "Green Logic",
  "1190": "Tripace",
  "1191": "Acard Technology Corp.",
  "1192": "Densan Co. Ltd",
  "1194": "Toucan Technology",
  "1195": "Ratoc System Inc",
  "1196": "Hytec Electronics Ltd",
  "1197": "Gage Applied Technologies",
  "1198": "Lambda Systems Inc",
  "1199": "Attachmate Corp.",
  "119A": "Mind/Share Inc.",
  "119B": "Omega Micro Inc.",
  "119C": "Information Technology Inst.",
  "119D": "Bug Sapporo Japan",
  "119E": "Fujitsu Microelectronics Ltd.",
  "119F": "Bull Hn Information Systems",
  "11A1": "Hamamatsu Photonics K.K.",
  "11A2": "Sierra Research and Technology",
  "11A3": "Deuretzbacher GmbH & Co. Eng. KG",
  "11A4": "Barco",
  "11A5": "MicroUnity Systems Engineering Inc.",
  "11A6": "Pure Data",
  "11A7": "Power Computing Corp.",
  "11A8": "Systech Corp.",
  "11A9": "InnoSys Inc.",
  "11AA": "Actel",
  "11AB": "Marvell Semiconductor",
  "11AC": "Canon Information Systems",
  "11AD": "Lite-On Technology Corp.",
  "11AE": "Scitex Corporation Ltd",
  "11AF": "Avid Technology, Inc.",
  "11B0": "Quicklogic Corp",
  "11B1": "Apricot Computers",
  "11B2": "Eastman Kodak",
  "11B3": "Barr Systems Inc.",
  "11B4": "Leitch Technology International",
  "11B5": "Radstone Technology Ltd.",
  "11B6": "United Video Corp",
  "11B7": "Motorola",
  "11B8": "Xpoint Technologies Inc",
  "11B9": "Pathlight Technology Inc.",
  "11BA": "Videotron Corp",
  "11BB": "Pyramid Technology",
  "11BC": "Network Peripherals Inc",
  "11BD": "Pinnacle system",
  "11BE": "International Microcircuits Inc",
  "11BF": "Astrodesign Inc.",
  "11C1": "LSI Corporation",
  "11C2": "Sand Microelectronics",
  "11C4": "Document Technologies Ind.",
  "11C5": "Shiva Corporatin",
  "11C6": "Dainippon Screen Mfg. Co",
  "11C7": "D.C.M. Data Systems",
  "11C8": "Dolphin Interconnect Solutions",
  "11C9": "MAGMA",
  "11CA": "LSI Systems Inc",
  "11CB": "Specialix International Ltd.",
  "11CC": "Michels & Kleberhoff Computer GmbH",
  "11CD": "HAL Computer Systems Inc.",
  "11CE": "Primary Rate Inc",
  "11CF": "Pioneer Electronic Corporation",
  "11D0": "BAE SYSTEMS - Manassas",
  "11D1": "AuraVision Corporation",
  "11D2": "Intercom Inc.",
  "11D3": "Trancell Systems Inc",
  "11D4": "Analog Devices, Inc.",
  "11D5": "Tahoma Technology",
  "11D6": "Tekelec Technologies",
  "11D7": "TRENTON Technology, Inc.",
  "11D8": "Image Technologies Development",
  "11D9": "Tec Corporation",
  "11DA": "Novell",
  "11DB": "Sega Enterprises Ltd",
  "11DC": "Questra Corp",
  "11DD": "Crosfield Electronics Ltd",
  "11DE": "Zoran Corporation",
  "11E1": "Gec Plessey Semi Inc",
  "11E2": "Samsung Information Systems America",
  "11E3": "Quicklogic Corp",
  "11E4": "Second Wave Inc",
  "11E5": "IIX Consulting",
  "11E6": "Mitsui-Zosen System Research",
  "11E8": "Digital Processing Systems Inc",
  "11E9": "Highwater Designs Ltd",
  "11EA": "Elsag Bailey",
  "11EB": "Formation, Inc",
  "11EC": "Coreco Inc",
  "11ED": "Mediamatics",
  "11EE": "Dome Imaging Systems Inc",
  "11EF": "Nicolet Technologies BV",
  "11F0": "Triya",
  "11F2": "Picture Tel Japan KK",
  "11F3": "Keithley Instruments, Inc",
  "11F4": "Kinetic Systems Corporation",
  "11F5": "Computing Devices Intl",
  "11F6": "Powermatic Data Systems Ltd",
  "11F7": "Scientific Atlanta",
  "11F8": "PMC-Sierra Inc.",
  "11F9": "I-Cube Inc",
  "11FA": "Kasan Electronics Co Ltd",
  "11FB": "Datel Inc",
  "11FD": "High Street Consultants",
  "11FE": "Comtrol Corp",
  "11FF": "Scion Corp",
  "1200": "CSS Corp",
  "1201": "Vista Controls Corp",
  "1202": "Network General Corp",
  "1203": "Bayer Corporation Agfa Div",
  "1204": "Lattice Semiconductor Corp",
  "1205": "Array Corp",
  "1206": "Amdahl Corp",
  "1208": "Parsytec GmbH",
  "1209": "Sci Systems Inc",
  "120A": "Synaptel",
  "120B": "Adaptive Solutions",
  "120D": "Compression Labs Inc.",
  "120E": "Cyclades Corporation",
  "120F": "Essential Communications",
  "1210": "Hyperparallel Technologies",
  "1211": "Braintech Inc",
  "1213": "Applied Intelligent Systems Inc",
  "1214": "Performance Technologies Inc",
  "1215": "Interware Co Ltd",
  "1216": "Purup-Eskofot A/S",
  "1217": "O2Micro Inc",
  "1218": "Hybricon Corp",
  "1219": "First Virtual Corp",
  "121A": "3dfx Interactive Inc",
  "121B": "Advanced Telecommunications Modules",
  "121C": "Nippon Texa Co Ltd",
  "121D": "LiPPERT Embedded Computers GmbH",
  "121E": "CSPI",
  "121F": "Arcus Technology Inc",
  "1220": "Ariel Corporation",
  "1221": "Contec Microelectronics Europe BV",
  "1222": "Ancor Communications Inc",
  "1223": "Artesyn Embedded Technologies",
  "1224": "Interactive Images",
  "1225": "Power I/O Inc.",
  "1227": "Tech-Source",
  "1228": "Norsk Elektro Optikk A/S",
  "1229": "Data Kinesis Inc.",
  "122A": "Integrated Telecom",
  "122B": "LG Industrial Systems Co. Ltd.",
  "122C": "sci-worx GmbH",
  "122D": "Aztech System Ltd",
  "122E": "Absolute Analysis",
  "122F": "Andrew Corp.",
  "1230": "Fishcamp Engineering",
  "1231": "Woodward McCoach Inc.",
  "1233": "Bus-Tech Inc.",
  "1234": "Technical Corp",
  "1236": "Sigma Designs, Inc",
  "1237": "Alta Technology Corp.",
  "1238": "Adtran",
  "1239": "The 3DO Company",
  "123A": "Visicom Laboratories Inc.",
  "123B": "Seeq Technology Inc.",
  "123C": "Century Systems Inc.",
  "123D": "Engineering Design Team Inc.",
  "123F": "C-Cube Microsystems",
  "1240": "Marathon Technologies Corp.",
  "1241": "DSC Communications",
  "1242": "JNI Corporation",
  "1243": "Delphax",
  "1244": "AVM AUDIOVISUELLES MKTG & Computer GmbH",
  "1245": "APD S.A.",
  "1246": "Dipix Technologies Inc",
  "1247": "Xylon Research Inc.",
  "1248": "Central Data Corp.",
  "1249": "Samsung Electronics Co. Ltd.",
  "124A": "AEG Electrocom GmbH",
  "124C": "Solitron Technologies Inc.",
  "124D": "Stallion Technologies",
  "124E": "Cylink",
  "124F": "Infortrend Technology Inc",
  "1250": "Hitachi Microcomputer System Ltd.",
  "1251": "VLSI Solution OY",
  "1253": "Guzik Technical Enterprises",
  "1254": "Linear Systems Ltd.",
  "1255": "Optibase Ltd.",
  "1256": "Perceptive Solutions Inc.",
  "1257": "Vertex Networks Inc.",
  "1258": "Gilbarco Inc.",
  "1259": "Allied Telesyn International",
  "125A": "ABB Power Systems",
  "125B": "Asix Electronics Corp.",
  "125C": "Aurora Technologies Inc.",
  "125D": "ESS Technology",
  "125E": "Specialvideo Engineering SRL",
  "125F": "Concurrent Technologies Inc.",
  "1260": "Intersil Corporation",
  "1261": "Matsushita-Kotobuki Electronics Indu",
  "1262": "ES Computer Co. Ltd.",
  "1263": "Sonic Solutions",
  "1264": "Aval Nagasaki Corp.",
  "1265": "Casio Computer Co. Ltd.",
  "1266": "Microdyne Corp.",
  "1267": "S.A. Telecommunications",
  "1268": "Tektronix",
  "1269": "Thomson-CSF/TTM",
  "126A": "Lexmark International Inc.",
  "126B": "Adax Inc.",
  "126C": "Nortel Networks Corp.",
  "126D": "Splash Technology Inc.",
  "126E": "Sumitomo Metal Industries Ltd.",
  "126F": "Silicon Motion",
  "1270": "Olympus Optical Co. Ltd.",
  "1271": "GW Instruments",
  "1272": "themrtaish",
  "1273": "Hughes Network Systems",
  "1274": "Ensoniq",
  "1275": "Network Appliance",
  "1276": "Switched Network Technologies Inc.",
  "1277": "Comstream",
  "1278": "Transtech Parallel Systems",
  "1279": "Transmeta Corp.",
  "127B": "Pixera Corp",
  "127C": "Crosspoint Solutions Inc.",
  "127D": "Vela Research LP",
  "127E": "Winnov L.P.",
  "127F": "Fujifilm",
  "1280": "Photoscript Group Ltd.",
  "1281": "Yokogawa Electronic Corp.",
  "1282": "Davicom Semiconductor Inc.",
  "1283": "Waldo",
  "1285": "Platform Technologies Inc.",
  "1286": "MAZeT GmbH",
  "1287": "LuxSonor Inc.",
  "1288": "Timestep Corp.",
  "1289": "AVC Technology Inc.",
  "128A": "Asante Technologies Inc.",
  "128B": "Transwitch Corp.",
  "128C": "Retix Corp.",
  "128D": "G2 Networks Inc.",
  "128F": "Tateno Dennou Inc.",
  "1290": "Sord Computer Corp.",
  "1291": "NCS Computer Italia",
  "1292": "Tritech Microelectronics Intl PTE",
  "1293": "Media Reality Technology",
  "1294": "Rhetorex Inc.",
  "1295": "Imagenation Corp.",
  "1296": "Kofax Image Products",
  "1297": "Shuttle Computer",
  "1298": "Spellcaster Telecommunications Inc.",
  "1299": "Knowledge Technology Laboratories",
  "129A": "Curtiss Wright Controls Electronic Systems",
  "129B": "Image Access",
  "129D": "CompCore Multimedia Inc.",
  "129E": "Victor Co. of Japan Ltd.",
  "129F": "OEC Medical Systems Inc.",
  "12A0": "Allen Bradley Co.",
  "12A1": "Simpact Inc",
  "12A2": "NewGen Systems Corp.",
  "12A3": "Lucent Technologies AMR",
  "12A4": "NTT Electronics Corp.",
  "12A5": "Vision Dynamics Ltd.",
  "12A6": "Scalable Networks Inc.",
  "12A7": "AMO GmbH",
  "12A8": "News Datacom",
  "12A9": "Xiotech Corp.",
  "12AA": "SDL Communications Inc.",
  "12AB": "Yuan Yuan Enterprise Co. Ltd.",
  "12AC": "MeasureX Corp.",
  "12AD": "MULTIDATA GmbH",
  "12AE": "Alteon Networks Inc.",
  "12AF": "TDK USA Corp.",
  "12B0": "Jorge Scientific Corp.",
  "12B1": "GammaLink",
  "12B2": "General Signal Networks",
  "12B3": "Interface Corp. Ltd.",
  "12B4": "Future Tel Inc.",
  "12B5": "Granite Systems Inc.",
  "12B7": "Acumen",
  "12B8": "Korg",
  "12B9": "3Com Corporation",
  "12BA": "Bittware, Inc",
  "12BB": "Nippon Unisoft Corp.",
  "12BC": "Array Microsystems",
  "12BD": "Computerm Corp.",
  "12BF": "Fujifilm Microdevices",
  "12C0": "Infimed",
  "12C1": "GMM Research Corp.",
  "12C2": "Mentec Ltd.",
  "12C3": "Holtek Microelectronics Inc.",
  "12C4": "Connect Tech Inc.",
  "12C5": "Picture Elements Inc.",
  "12C6": "Mitani Corp.",
  "12C7": "Dialogic Corp.",
  "12C8": "G Force Co. Ltd.",
  "12C9": "Gigi Operations",
  "12CA": "Integrated Computing Engines, Inc.",
  "12CB": "Antex Electronics Corp.",
  "12CC": "Pluto Technologies International",
  "12CD": "Aims Lab",
  "12CE": "Netspeed Inc.",
  "12CF": "Prophet Systems Inc.",
  "12D0": "GDE Systems Inc.",
  "12D1": "Huawei Technologies Co., Ltd.",
  "12D3": "Vingmed Sound A/S",
  "12D4": "Ulticom, Inc.",
  "12D5": "Equator Technologies",
  "12D6": "Analogic Corp.",
  "12D7": "Biotronic SRL",
  "12D8": "Pericom Semiconductor",
  "12D9": "Aculab Plc.",
  "12DA": "TrueTime",
  "12DB": "Annapolis Micro Systems Inc.",
  "12DC": "Symicron Computer Communication Ltd.",
  "12DD": "Management Graphics Inc.",
  "12DE": "Rainbow Technologies",
  "12DF": "SBS Technologies Inc.",
  "12E0": "Chase Research PLC",
  "12E1": "Nintendo Co. Ltd.",
  "12E2": "Datum Inc. Bancomm-Timing Division",
  "12E3": "Imation Corp. - Medical Imaging Syst",
  "12E4": "Brooktrout Technology Inc.",
  "12E6": "Cirel Systems",
  "12E7": "Sebring Systems Inc",
  "12E8": "CRISC Corp.",
  "12E9": "GE Spacenet",
  "12EB": "Aureal Semiconductor",
  "12EC": "3A International Inc.",
  "12ED": "Optivision Inc.",
  "12EE": "Orange Micro, Inc.",
  "12EF": "Vienna Systems",
  "12F0": "Pentek",
  "12F1": "Sorenson Vision Inc.",
  "12F2": "Gammagraphx Inc.",
  "12F4": "Megatel",
  "12F5": "Forks",
  "12F7": "Cognex",
  "12F8": "Electronic-Design GmbH",
  "12F9": "FourFold Technologies",
  "12FB": "Spectrum Signal Processing",
  "12FC": "Capital Equipment Corp",
  "12FE": "esd Electronic System Design GmbH",
  "1303": "Innovative Integration",
  "1304": "Juniper Networks Inc.",
  "1307": "ComputerBoards",
  "1308": "Jato Technologies Inc.",
  "130A": "Mitsubishi Electric Microcomputer",
  "130B": "Colorgraphic Communications Corp",
  "130F": "Advanet Inc.",
  "1310": "Gespac",
  "1312": "Microscan Systems Inc",
  "1313": "Yaskawa Electric Co.",
  "1316": "Teradyne Inc.",
  "1317": "ADMtek Inc",
  "1318": "Packet Engines, Inc.",
  "1319": "Forte Media",
  "131F": "SIIG",
  "1325": "austriamicrosystems",
  "1326": "Seachange International",
  "1328": "CIFELLI SYSTEMS CORPORATION",
  "1331": "RadiSys Corporation",
  "1332": "Curtiss-Wright Controls Embedded Computing",
  "1335": "Videomail Inc.",
  "133D": "Prisa Networks",
  "133F": "SCM Microsystems",
  "1342": "Promax Systems Inc",
  "1344": "Micron Technology, Inc.",
  "1347": "Spectracom Corporation",
  "134A": "DTC Technology Corp.",
  "134B": "ARK Research Corp.",
  "134C": "Chori Joho System Co. Ltd",
  "134D": "PCTEL Inc.",
  "135A": "Brain Boxes Limited",
  "135B": "Giganet Inc.",
  "135C": "Quatech Inc",
  "135D": "ABB Network Partner AB",
  "135E": "Sealevel Systems Inc.",
  "135F": "I-Data International A-S",
  "1360": "Meinberg Funkuhren GmbH & Co. KG",
  "1361": "Soliton Systems K.K.",
  "1363": "Phoenix Technologies Ltd",
  "1365": "Hypercope Corp.",
  "1366": "Teijin Seiki Co. Ltd.",
  "1367": "Hitachi Zosen Corporation",
  "1368": "Skyware Corporation",
  "1369": "Digigram",
  "136B": "Kawasaki Steel Corporation",
  "136C": "Adtek System Science Co Ltd",
  "1375": "Boeing - Sunnyvale",
  "137A": "Mark Of The Unicorn Inc",
  "137B": "PPT Vision",
  "137C": "Iwatsu Electric Co Ltd",
  "137D": "Dynachip Corporation",
  "137E": "Patriot Scientific Corp.",
  "1380": "Sanritz Automation Co LTC",
  "1381": "Brains Co. Ltd",
  "1382": "Marian - Electronic & Software",
  "1384": "Stellar Semiconductor Inc",
  "1385": "Netgear",
  "1387": "Curtiss-Wright Controls Electronic Systems",
  "1388": "Hitachi Information Technology Co Ltd",
  "1389": "Applicom International",
  "138A": "Validity Sensors, Inc.",
  "138B": "Tokimec Inc",
  "138E": "Basler GMBH",
  "138F": "Patapsco Designs Inc",
  "1390": "Concept Development Inc.",
  "1393": "Moxa Technologies Co Ltd",
  "1394": "Level One Communications",
  "1395": "Ambicom Inc",
  "1396": "Cipher Systems Inc",
  "1397": "Cologne Chip Designs GmbH",
  "1398": "Clarion Co. Ltd",
  "139A": "Alacritech Inc",
  "139D": "Xstreams PLC/ EPL Limited",
  "139E": "Echostar Data Networks",
  "13A0": "Crystal Group Inc",
  "13A1": "Kawasaki Heavy Industries Ltd",
  "13A3": "HI-FN Inc.",
  "13A4": "Rascom Inc",
  "13A7": "amc330",
  "13A8": "Exar Corp.",
  "13A9": "Siemens Healthcare",
  "13AA": "Nortel Networks - BWA Division",
  "13AF": "T.Sqware",
  "13B1": "Tamura Corporation",
  "13B4": "Wellbean Co Inc",
  "13B5": "ARM Ltd",
  "13B6": "DLoG Gesellschaft für elektronische Datentechnik mbH",
  "13B8": "Nokia Telecommunications OY",
  "13BD": "Sharp Corporation",
  "13BF": "Sharewave Inc",
  "13C0": "Microgate Corp.",
  "13C1": "LSI",
  "13C2": "Technotrend Systemtechnik GMBH",
  "13C3": "Janz Computer AG",
  "13C7": "Blue Chip Technology Ltd",
  "13CC": "Metheus Corporation",
  "13CF": "Studio Audio & Video Ltd",
  "13D0": "B2C2 Inc",
  "13D1": "AboCom Systems, Inc",
  "13D4": "Graphics Microsystems Inc",
  "13D6": "K.I. Technology Co Ltd",
  "13D7": "Toshiba Engineering Corporation",
  "13D8": "Phobos Corporation",
  "13D9": "Apex Inc",
  "13DC": "Netboost Corporation",
  "13DE": "ABB Robotics Products AB",
  "13DF": "E-Tech Inc.",
  "13E0": "GVC Corporation",
  "13E3": "Nest Inc",
  "13E4": "Calculex Inc",
  "13E5": "Telesoft Design Ltd",
  "13E9": "Intraserver Technology Inc",
  "13EA": "Dallas Semiconductor",
  "13F0": "IC Plus Corporation",
  "13F1": "OCE - Industries S.A.",
  "13F4": "Troika Networks Inc",
  "13F6": "C-Media Electronics Inc.",
  "13F9": "NTT Advanced Technology Corp.",
  "13FA": "Pentland Systems Ltd.",
  "13FB": "Aydin Corp",
  "13FD": "Micro Science Inc",
  "13FE": "Advantech Co., Ltd.",
  "13FF": "Silicon Spice Inc.",
  "1400": "ArtX Inc",
  "1402": "Meilhaus Electronic GmbH Germany",
  "1404": "Fundamental Software Inc",
  "1406": "Oce Print Logics Technologies S.A.",
  "1407": "Lava Computer MFG Inc.",
  "1408": "Aloka Co. Ltd",
  "1409": "SUNIX Co., Ltd.",
  "140A": "DSP Research Inc",
  "140B": "Ramix Inc",
  "140D": "Matsushita Electric Works Ltd",
  "140F": "Salient Systems Corp",
  "1412": "IC Ensemble, Inc.",
  "1413": "Addonics",
  "1415": "Oxford Semiconductor Ltd - now part of PLX Technology",
  "1418": "Kyushu Electronics Systems Inc",
  "1419": "Excel Switching Corp",
  "141B": "Zoom Telephonics Inc",
  "141E": "Fanuc Co. Ltd",
  "141F": "Visiontech Ltd",
  "1420": "Psion Dacom PLC",
  "1425": "Chelsio Communications",
  "1428": "Edec Co Ltd",
  "1429": "Unex Technology Corp.",
  "142A": "Kingmax Technology Inc",
  "142B": "Radiolan",
  "142C": "Minton Optic Industry Co Ltd",
  "142D": "Pixstream Inc",
  "1430": "ITT Aerospace/Communications Division",
  "1433": "Eltec Elektronik AG",
  "1435": "RTD Embedded Technologies, Inc.",
  "1436": "CIS Technology Inc",
  "1437": "Nissin Inc Co",
  "1438": "Atmel-Dream",
  "143F": "Lightwell Co Ltd - Zax Division",
  "1441": "Agie SA.",
  "1443": "Unibrain S.A.",
  "1445": "Logical Co Ltd",
  "1446": "Graphin Co., LTD",
  "1447": "Aim GMBH",
  "1448": "Alesis Studio",
  "144A": "ADLINK Technology Inc",
  "144B": "Loronix Information Systems, Inc.",
  "144D": "sanyo",
  "1450": "Octave Communications Ind.",
  "1451": "SP3D Chip Design GMBH",
  "1453": "Mycom Inc",
  "1458": "Giga-Byte Technologies",
  "145C": "Cryptek",
  "145F": "Baldor Electric Company",
  "1460": "Dynarc Inc",
  "1462": "Micro-Star International Co Ltd",
  "1463": "Fast Corporation",
  "1464": "Interactive Circuits & Systems Ltd",
  "1468": "Ambit Microsystems Corp.",
  "1469": "Cleveland Motion Controls",
  "146C": "Ruby Tech Corp.",
  "146D": "Tachyon Inc.",
  "146E": "WMS Gaming",
  "1471": "Integrated Telecom Express Inc",
  "1473": "Zapex Technologies Inc",
  "1474": "Doug Carson & Associates",
  "1477": "Net Insight",
  "1478": "Diatrend Corporation",
  "147B": "Abit Computer Corp.",
  "147F": "Nihon Unisys Ltd.",
  "1482": "Isytec - Integrierte Systemtechnik Gmbh",
  "1483": "Labway Coporation",
  "1485": "Erma - Electronic GMBH",
  "1489": "KYE Systems Corporation",
  "148A": "Opto 22",
  "148B": "Innomedialogic Inc.",
  "148C": "C.P. Technology Co. Ltd",
  "148D": "Digicom Systems Inc.",
  "148E": "OSI Plus Corporation",
  "148F": "Plant Equipment Inc.",
  "1490": "TC Labs Pty Ltd.",
  "1491": "Futronic",
  "1493": "Maker Communications",
  "1495": "Tokai Communications Industry Co. Ltd",
  "1496": "Joytech Computer Co. Ltd.",
  "1497": "SMA Technologie AG",
  "1498": "Tews Technologies",
  "1499": "Micro-Technology Co Ltd",
  "149A": "Andor Technology Ltd",
  "149B": "Seiko Instruments Inc",
  "149E": "Mapletree Networks Inc.",
  "149F": "Lectron Co Ltd",
  "14A0": "Softing AG",
  "14A2": "Millennium Engineering Inc",
  "14A4": "GVC/BCM Advanced Research",
  "14A9": "Hivertec Inc.",
  "14AB": "Mentor Graphics Corp.",
  "14B1": "Nextcom K.K.",
  "14B3": "Xpeed Inc.",
  "14B4": "Philips Business Electronics B.V.",
  "14B5": "Creamware GmbH",
  "14B6": "Quantum Data Corp.",
  "14B7": "Proxim Inc.",
  "14B9": "Aironet Wireless Communication",
  "14BA": "Internix Inc.",
  "14BB": "Semtech Corporation",
  "14BE": "L3 Communications",
  "14C0": "Compal Electronics, Inc.",
  "14C1": "Myricom Inc.",
  "14C2": "DTK Computer",
  "14C4": "Iwasaki Information Systems Co Ltd",
  "14C5": "ABB AB (Sweden)",
  "14C6": "Data Race Inc",
  "14C7": "Modular Technology Ltd.",
  "14C8": "Turbocomm Tech Inc",
  "14C9": "Odin Telesystems Inc",
  "14CB": "Billionton Systems Inc./Cadmus Micro Inc",
  "14CD": "Universal Scientific Ind.",
  "14CF": "TEK Microsystems Inc.",
  "14D4": "Panacom Technology Corporation",
  "14D5": "Nitsuko Corporation",
  "14D6": "Accusys Inc",
  "14D7": "Hirakawa Hewtech Corp",
  "14D8": "Hopf Elektronik GMBH",
  "14D9": "Alpha Processor Inc",
  "14DB": "Avlab Technology Inc.",
  "14DC": "Amplicon Liveline Limited",
  "14DD": "Imodl Inc.",
  "14DE": "Applied Integration Corporation",
  "14E3": "Amtelco",
  "14E4": "Broadcom",
  "14EA": "Planex Communications, Inc.",
  "14EB": "Seiko Epson Corporation",
  "14EC": "Acqiris",
  "14ED": "Datakinetics Ltd",
  "14EF": "Carry Computer Eng. Co Ltd",
  "14F1": "Conexant",
  "14F2": "Mobility Electronics, Inc.",
  "14F4": "Tokyo Electronic Industry Co. Ltd.",
  "14F5": "Sopac Ltd",
  "14F6": "Coyote Technologies LLC",
  "14F7": "Wolf Technology Inc",
  "14F8": "Audiocodes Inc",
  "14F9": "AG Communications",
  "14FB": "Transas Marine (UK) Ltd",
  "14FC": "Quadrics Ltd",
  "14FD": "Silex Technology Inc.",
  "14FE": "Archtek Telecom Corp.",
  "14FF": "Twinhead International Corp.",
  "1501": "Banksoft Canada Ltd",
  "1502": "Mitsubishi Electric Logistics Support Co",
  "1503": "Kawasaki LSI USA Inc",
  "1504": "Kaiser Electronics",
  "1506": "Chameleon Systems Inc",
  "1507": "Htec Ltd.",
  "1509": "First International Computer Inc",
  "150B": "Yamashita Systems Corp",
  "150C": "Kyopal Co Ltd",
  "150D": "Warpspped Inc",
  "150E": "C-Port Corporation",
  "150F": "Intec GMBH",
  "1510": "Behavior Tech Computer Corp",
  "1511": "Centillium Technology Corp",
  "1512": "Rosun Technologies Inc",
  "1513": "Raychem",
  "1514": "TFL LAN Inc",
  "1515": "ICS Advent",
  "1516": "Myson Technology Inc",
  "1517": "Echotek Corporation",
  "1518": "Kontron Modular Computers GmbH (PEP Modular Computers GMBH)",
  "1519": "Telefon Aktiebolaget LM Ericsson",
  "151A": "Globetek Inc.",
  "151B": "Combox Ltd",
  "151C": "Digital Audio Labs Inc",
  "151D": "Fujitsu Computer Products Of America",
  "151E": "Matrix Corp.",
  "151F": "Topic Semiconductor Corp",
  "1520": "Chaplet System Inc",
  "1521": "Bell Corporation",
  "1522": "Mainpine Limited",
  "1523": "Music Semiconductors",
  "1524": "ENE Technology Inc",
  "1525": "Impact Technologies",
  "1526": "ISS Inc",
  "1527": "Solectron",
  "1528": "Acksys",
  "1529": "American Microsystems Inc",
  "152A": "Quickturn Design Systems",
  "152B": "Flytech Technology Co Ltd",
  "152C": "Macraigor Systems LLC",
  "152D": "Quanta Computer Inc",
  "152E": "Melec Inc",
  "152F": "Philips - Crypto",
  "1532": "Echelon Corporation",
  "1533": "Baltimore",
  "1534": "Road Corporation",
  "1535": "Evergreen Technologies Inc",
  "1537": "Datalex Communcations",
  "1538": "Aralion Inc.",
  "1539": "Atelier Informatiques et Electronique Et",
  "153A": "ONO Sokki",
  "153B": "Terratec Electronic GMBH",
  "153C": "Antal Electronic",
  "153D": "Filanet Corporation",
  "153E": "Techwell Inc",
  "153F": "MIPS Technologies, Inc",
  "1540": "Provideo Multimedia Co Ltd",
  "1541": "Telocity Inc.",
  "1542": "Vivid Technology Inc",
  "1543": "Silicon Laboratories",
  "1544": "DCM Technologies Ltd.",
  "1545": "VisionTek",
  "1546": "IOI Technology Corp.",
  "1547": "Mitutoyo Corporation",
  "1548": "Jet Propulsion Laboratory",
  "1549": "Interconnect Systems Solutions",
  "154A": "Max Technologies Inc.",
  "154B": "Computex Co Ltd",
  "154C": "Visual Technology Inc.",
  "154D": "PAN International Industrial Corp",
  "154E": "Servotest Ltd",
  "154F": "Stratabeam Technology",
  "1550": "Open Network Co Ltd",
  "1551": "Smart Electronic Development GMBH",
  "1553": "Chicony Electronics Co Ltd",
  "1554": "Prolink Microsystems Corp.",
  "1555": "Gesytec GmbH",
  "1556": "PLDA",
  "1557": "Mediastar Co. Ltd",
  "1558": "Clevo/Kapok Computer",
  "1559": "SI Logic Ltd",
  "155A": "Innomedia Inc",
  "155B": "Protac International Corp",
  "155C": "s",
  "155D": "MAC System Co Ltd",
  "155E": "KUKA Roboter GmbH",
  "155F": "Perle Systems Limited",
  "1560": "Terayon Communications Systems",
  "1561": "Viewgraphics Inc",
  "1562": "Symbol Technologies, Inc.",
  "1563": "A-Trend Technology Co Ltd",
  "1564": "Yamakatsu Electronics Industry Co Ltd",
  "1565": "Biostar Microtech Intl Corp",
  "1566": "Ardent Technologies Inc",
  "1567": "Jungsoft",
  "1568": "DDK Electronics Inc",
  "1569": "Palit Microsystems Inc",
  "156A": "Avtec Systems Inc",
  "156B": "S2io Inc",
  "156C": "Vidac Electronics GMBH",
  "156D": "Alpha-Top Corp",
  "156E": "Alfa Inc.",
  "156F": "M-Systems Flash Disk Pioneers Ltd",
  "1570": "Lecroy Corporation",
  "1571": "Contemporary Controls",
  "1572": "Otis Elevator Company",
  "1573": "Lattice - Vantis",
  "1574": "Fairchild Semiconductor",
  "1575": "Voltaire Advanced Data Security Ltd",
  "1576": "Viewcast Com",
  "1578": "Hitt",
  "1579": "Dual Technology Corporation",
  "157A": "Japan Elecronics Ind. Inc",
  "157B": "Star Multimedia Corp.",
  "157C": "Eurosoft (UK)",
  "157D": "Gemflex Networks",
  "157E": "Transition Networks",
  "157F": "PX Instruments Technology Ltd",
  "1580": "Primex Aerospace Co.",
  "1581": "SEH Computertechnik GMBH",
  "1582": "Cytec Corporation",
  "1583": "Inet Technologies Inc",
  "1584": "Vetronix Corporation Engenharia Ltda",
  "1585": "Marconi Commerce Systems SRL",
  "1586": "Lancast Inc",
  "1587": "Konica Corporation",
  "1588": "Solidum Systems Corp",
  "1589": "Atlantek Microsystems Pty Ltd",
  "158A": "Digalog Systems Inc",
  "158B": "Allied Data Technologies",
  "158C": "Hitachi Semiconductor & Devices Sales Co",
  "158D": "Point Multimedia Systems",
  "158E": "Lara Technology Inc",
  "158F": "Ditect Coop",
  "1590": "3pardata Inc.",
  "1591": "ARN",
  "1592": "Syba Tech Ltd.",
  "1593": "Bops Inc",
  "1594": "Netgame Ltd",
  "1595": "Diva Systems Corp.",
  "1596": "Folsom Research Inc",
  "1597": "Memec Design Services",
  "1598": "Granite Microsystems",
  "1599": "Delta Electronics Inc",
  "159A": "General Instrument",
  "159B": "Faraday Technology Corp",
  "159C": "Stratus Computer Systems",
  "159D": "Ningbo Harrison Electronics Co Ltd",
  "159E": "A-Max Technology Co Ltd",
  "159F": "Galea Network Security",
  "15A0": "Compumaster SRL",
  "15A1": "Geocast Network Systems Inc",
  "15A2": "Catalyst Enterprises Inc",
  "15A3": "Italtel",
  "15A4": "X-Net OY",
  "15A5": "Toyota MACS Inc",
  "15A6": "Sunlight Ultrasound Technologies Ltd",
  "15A7": "SSE Telecom Inc",
  "15A8": "Shanghai Communications Technologies Cen",
  "15AA": "Moreton Bay",
  "15AB": "Bluesteel Networks Inc",
  "15AC": "North Atlantic Instruments",
  "15AD": "VMware Inc.",
  "15AE": "Amersham Pharmacia Biotech",
  "15B0": "Zoltrix International Limited",
  "15B1": "Source Technology Inc",
  "15B2": "Mosaid Technologies Inc.",
  "15B3": "Mellanox Technology",
  "15B4": "CCI/Triad",
  "15B5": "Cimetrics Inc",
  "15B6": "Texas Memory Systems Inc",
  "15B7": "Sandisk Corp.",
  "15B8": "Addi-Data GMBH",
  "15B9": "Maestro Digital Communications",
  "15BA": "Impacct Technology Corp",
  "15BB": "Portwell Inc",
  "15BC": "Agilent Technologies",
  "15BD": "DFI Inc.",
  "15BE": "Sola Electronics",
  "15BF": "High Tech Computer Corp (HTC)",
  "15C0": "BVM Limited",
  "15C1": "Quantel",
  "15C2": "Newer Technology Inc",
  "15C3": "Taiwan Mycomp Co Ltd",
  "15C4": "EVSX Inc",
  "15C5": "Procomp Informatics Ltd",
  "15C6": "Technical University Of Budapest",
  "15C7": "Tateyama System Laboratory Co Ltd",
  "15C8": "Penta Media Co. Ltd",
  "15C9": "Serome Technology Inc",
  "15CA": "Bitboys OY",
  "15CB": "AG Electronics Ltd",
  "15CC": "Hotrail Inc.",
  "15CD": "Dreamtech Co Ltd",
  "15CE": "Genrad Inc.",
  "15CF": "Hilscher GMBH",
  "15D1": "Infineon Technologies AG",
  "15D2": "FIC (First International Computer Inc)",
  "15D3": "NDS Technologies Israel Ltd",
  "15D4": "Iwill Corporation",
  "15D5": "Tatung Co.",
  "15D6": "Entridia Corporation",
  "15D7": "Rockwell-Collins Inc",
  "15D8": "Cybernetics Technology Co Ltd",
  "15D9": "Super Micro Computer Inc",
  "15DA": "Cyberfirm Inc.",
  "15DB": "Applied Computing Systems Inc.",
  "15DC": "Litronic Inc.",
  "15DD": "Sigmatel Inc.",
  "15DE": "Malleable Technologies Inc",
  "15E0": "Cacheflow Inc",
  "15E1": "Voice Technologies Group",
  "15E2": "Quicknet Technologies Inc",
  "15E3": "Networth Technologies Inc",
  "15E4": "VSN Systemen BV",
  "15E5": "Valley Technologies Inc",
  "15E6": "Agere Inc.",
  "15E7": "GET Engineering Corp.",
  "15E8": "National Datacomm Corp.",
  "15E9": "Pacific Digital Corp.",
  "15EA": "Tokyo Denshi Sekei K.K.",
  "15EB": "Drsearch GMBH",
  "15EC": "Beckhoff Automation GmbH",
  "15ED": "Macrolink Inc",
  "15EE": "IN Win Development Inc.",
  "15EF": "Intelligent Paradigm Inc",
  "15F0": "B-Tree Systems Inc",
  "15F1": "Times N Systems Inc",
  "15F2": "SPOT Imaging Solutions a division of Diagnostic Instruments, Inc",
  "15F3": "Digitmedia Corp.",
  "15F4": "Valuesoft",
  "15F5": "Power Micro Research",
  "15F6": "Extreme Packet Device Inc",
  "15F7": "Banctec",
  "15F8": "Koga Electronics Co",
  "15F9": "Zenith Electronics Co",
  "15FA": "Axzam Corporation",
  "15FB": "Zilog Inc.",
  "15FC": "Techsan Electronics Co Ltd",
  "15FD": "N-Cubed.Net",
  "15FE": "Kinpo Electronics Inc",
  "15FF": "Fastpoint Technologies Inc.",
  "1600": "Northrop Grumman - Canada Ltd",
  "1601": "Tenta Technology",
  "1602": "Prosys-TEC Inc.",
  "1603": "Nokia Wireless Business Communications",
  "1604": "Central System Research Co Ltd",
  "1605": "Pairgain Technologies",
  "1606": "Europop AG",
  "1607": "Lava Semiconductor Manufacturing Inc.",
  "1608": "Automated Wagering International",
  "1609": "Sciemetric Instruments Inc",
  "160A": "Kollmorgen Servotronix",
  "160B": "Onkyo Corp.",
  "160C": "Oregon Micro Systems Inc.",
  "160D": "Aaeon Electronics Inc",
  "160E": "CML Emergency Services",
  "160F": "ITEC Co Ltd",
  "1610": "Tottori Sanyo Electric Co Ltd",
  "1611": "Bel Fuse Inc.",
  "1612": "Telesynergy Research Inc.",
  "1613": "System Craft Inc.",
  "1614": "Jace Tech Inc.",
  "1615": "Equus Computer Systems Inc",
  "1616": "Iotech Inc.",
  "1617": "Rapidstream Inc",
  "1618": "Esec SA",
  "1619": "FarSite Communications Limited",
  "161B": "Mobilian Israel Ltd",
  "161C": "Berkshire Products",
  "161D": "Gatec",
  "161E": "Kyoei Sangyo Co Ltd",
  "161F": "Arima Computer Corporation",
  "1620": "Sigmacom Co Ltd",
  "1621": "Lynx Studio Technology Inc",
  "1622": "Nokia Home Communications",
  "1623": "KRF Tech Ltd",
  "1624": "CE Infosys GMBH",
  "1625": "Warp Nine Engineering",
  "1626": "TDK Semiconductor Corp.",
  "1627": "BCom Electronics Inc",
  "1629": "Kongsberg Spacetec a.s.",
  "162A": "Sejin Computerland Co Ltd",
  "162B": "Shanghai Bell Company Limited",
  "162C": "C&H Technologies Inc",
  "162D": "Reprosoft Co Ltd",
  "162E": "Margi Systems Inc",
  "162F": "Rohde & Schwarz GMBH & Co KG",
  "1630": "Sky Computers Inc",
  "1631": "NEC Computer International",
  "1632": "Verisys Inc",
  "1633": "Adac Corporation",
  "1634": "Visionglobal Network Corp.",
  "1635": "Decros / S.ICZ a.s.",
  "1636": "Jean Company Ltd",
  "1637": "NSI",
  "1638": "Eumitcom Technology Inc",
  "163A": "Air Prime Inc",
  "163B": "Glotrex Co Ltd",
  "163C": "intel",
  "163D": "Heidelberg Digital LLC",
  "163E": "3dpower",
  "163F": "Renishaw PLC",
  "1640": "Intelliworxx Inc",
  "1641": "MKNet Corporation",
  "1642": "Bitland",
  "1643": "Hajime Industries Ltd",
  "1644": "Western Avionics Ltd",
  "1645": "Quick-Serv. Computer Co. Ltd",
  "1646": "Nippon Systemware Co Ltd",
  "1647": "Hertz Systemtechnik GMBH",
  "1648": "MeltDown Systems LLC",
  "1649": "Jupiter Systems",
  "164A": "Aiwa Co. Ltd",
  "164C": "Department Of Defense",
  "164D": "Ishoni Networks",
  "164E": "Micrel Inc.",
  "164F": "Datavoice (Pty) Ltd.",
  "1650": "Admore Technology Inc.",
  "1651": "Chaparral Network Storage",
  "1652": "Spectrum Digital Inc.",
  "1653": "Nature Worldwide Technology Corp",
  "1654": "Sonicwall Inc",
  "1655": "Dazzle Multimedia Inc.",
  "1656": "Insyde Software Corp",
  "1657": "Brocade Communications Systems",
  "1658": "Med Associates Inc.",
  "1659": "Shiba Denshi Systems Inc.",
  "165A": "Epix Inc.",
  "165B": "Real-Time Digital Inc.",
  "165C": "Kondo Kagaku",
  "165D": "Hsing Tech. Enterprise Co. Ltd.",
  "165E": "Hyunju Computer Co. Ltd.",
  "165F": "Comartsystem Korea",
  "1660": "Network Security Technologies Inc. (NetSec)",
  "1661": "Worldspace Corp.",
  "1662": "Int Labs",
  "1663": "Elmec Inc. Ltd.",
  "1664": "Fastfame Technology Co. Ltd.",
  "1665": "Edax Inc.",
  "1666": "Norpak Corporation",
  "1667": "CoSystems Inc.",
  "1668": "Actiontec Electronics Inc.",
  "166A": "Komatsu Ltd.",
  "166B": "Supernet Inc.",
  "166C": "Shade Ltd.",
  "166D": "Sibyte Inc.",
  "166E": "Schneider Automation Inc.",
  "166F": "Televox Software Inc.",
  "1670": "Rearden Steel",
  "1671": "Atan Technology Inc.",
  "1672": "Unitec Co. Ltd.",
  "1673": "pctel",
  "1675": "Square Wave Technology",
  "1676": "Emachines Inc.",
  "1677": "Bernecker + Rainer",
  "1678": "INH Semiconductor",
  "1679": "Tokyo Electron Device Ltd.",
  "167F": "iba AG",
  "1680": "Dunti Corp.",
  "1681": "Hercules",
  "1682": "PINE Technology, Ltd.",
  "1688": "CastleNet Technology Inc.",
  "168A": "Utimaco Safeware AG",
  "168B": "Circut Assembly Corp.",
  "168C": "Atheros Communications Inc.",
  "168D": "NMI Electronics Ltd.",
  "168E": "Hyundai MultiCAV Computer Co. Ltd.",
  "168F": "KDS Innotech Corp.",
  "1690": "NetContinuum, Inc.",
  "1693": "FERMA",
  "1695": "EPoX Computer Co., Ltd.",
  "16AE": "SafeNet Inc.",
  "16B3": "CNF Mobile Solutions",
  "16B8": "Sonnet Technologies, Inc.",
  "16CA": "Cenatek Inc.",
  "16CB": "Minolta Co. Ltd.",
  "16CC": "Inari Inc.",
  "16D0": "Systemax",
  "16E0": "Third Millenium Test Solutions, Inc.",
  "16E5": "Intellon Corporation",
  "16EC": "U.S. Robotics",
  "16F0": "LaserLinc Inc.",
  "16F1": "Adicti Corp.",
  "16F3": "Jetway Information Co., Ltd",
  "16F6": "VideoTele.com Inc.",
  "1700": "Antara LLC",
  "1701": "Interactive Computer Products Inc.",
  "1702": "Internet Machines Corp.",
  "1703": "Desana Systems",
  "1704": "Clearwater Networks",
  "1705": "Digital First",
  "1706": "Pacific Broadband Communications",
  "1707": "Cogency Semiconductor Inc.",
  "1708": "Harris Corp.",
  "1709": "Zarlink Semiconductor",
  "170A": "Alpine Electronics Inc.",
  "170B": "NetOctave Inc.",
  "170C": "YottaYotta Inc.",
  "170D": "SensoMotoric Instruments GmbH",
  "170E": "San Valley Systems, Inc.",
  "170F": "Cyberdyne Inc.",
  "1710": "Pelago Networks",
  "1711": "MyName Technologies, Inc.",
  "1712": "NICE Systems Inc.",
  "1713": "TOPCON Corp.",
  "1725": "Vitesse Semiconductor",
  "1734": "Fujitsu-Siemens Computers GmbH",
  "1737": "LinkSys",
  "173B": "Altima Communications Inc.",
  "1743": "Peppercon AG",
  "174B": "PC Partner Limited",
  "1752": "Global Brands Manufacture Ltd.",
  "1753": "TeraRecon, Inc.",
  "1755": "Alchemy Semiconductor Inc.",
  "176A": "General Dynamics Canada",
  "1775": "General Electric",
  "1789": "Ennyah Technologies Corp",
  "1793": "Unitech Electronics Co., Ltd",
  "17A1": "Tascorp",
  "17A7": "Start Network Technology Co., Ltd.",
  "17AA": "Legend Ltd. (Beijing)",
  "17AB": "Phillips Components",
  "17AF": "Hightech Information Systems, Ltd.",
  "17BE": "Philips Semiconductors",
  "17C0": "Wistron Corp.",
  "17C4": "Movita",
  "17CC": "NetChip",
  "17cd": "Cadence Design Systems",
  "17D5": "Neterion Inc.",
  "17DB": "Cray, Inc.",
  "17E9": "DH electronics GmbH / Sabrent",
  "17EE": "Connect Components, Ltd.",
  "17F3": "RDC Semiconductor Co., Ltd.",
  "17FE": "INPROCOMM",
  "1813": "Ambient Technologies Inc",
  "1814": "Ralink Technology, Corp.",
  "1815": "devolo AG",
  "1820": "InfiniCon Systems, Inc.",
  "1824": "Avocent",
  "1841": "Panda Platinum",
  "1860": "Primagraphics Ltd.",
  "186C": "Humusoft S.R.O",
  "1887": "Elan Digital Systems Ltd",
  "1888": "Varisys Limited",
  "188D": "Millogic Ltd.",
  "1890": "Egenera, Inc.",
  "18BC": "Info-Tek Corp.",
  "18C9": "ARVOO Engineering BV",
  "18CA": "XGI Technology Inc",
  "18F1": "Spectrum Systementwicklung Microelectronic GmbH",
  "18F4": "Napatech A/S",
  "18F7": "Commtech, Inc.",
  "18FB": "Resilience Corporation",
  "1904": "Ritmo",
  "1905": "WIS Technology, Inc.",
  "1910": "Seaway Networks",
  "1912": "Renesas Electronics",
  "1931": "Option NV",
  "1941": "Stelar",
  "1954": "One Stop Systems, Inc.",
  "1969": "Atheros Communications",
  "1971": "AGEIA Technologies, Inc.",
  "197B": "JMicron Technology Corp.",
  "198A": "Nallatech",
  "1991": "Topstar Digital Technologies Co., Ltd.",
  "19A2": "ServerEngines",
  "19A8": "DAQDATA GmbH",
  "19AC": "Kasten Chase Applied Research",
  "19B6": "Mikrotik",
  "19E2": "Vector Informatik GmbH",
  "19E3": "DDRdrive LLC",
  "1A08": "Linux Networx",
  "1a41": "Tilera Corporation",
  "1A42": "Imaginant",
  "1B13": "Jaton Corporation USA",
  "1B21": "Asustek - ASMedia Technology Inc.",
  "1B6F": "Etron",
  "1B73": "Fresco Logic Inc.",
  "1B91": "Averna",
  "1BAD": "ReFLEX CES",
  "1C0F": "Monarch Innovative Technologies Pvt Ltds",
  "1C32": "Highland Technology, Inc.",
  "1c39": "Thomson Video Networks",
  "1DE1": "Tekram",
  "1FCF": "Miranda Technologies Ltd.",
  "2001": "Temporal Research Ltd",
  "2646": "Kingston Technology Co.",
  "270F": "ChainTek Computer Co. Ltd.",
  "2EC1": "Zenic Inc",
  "3388": "Hint Corp.",
  "3411": "Quantum Designs (H.K.) Inc.",
  "3513": "ARCOM Control Systems Ltd.",
  "38EF": "4links",
  "3D3D": "3Dlabs, Inc. Ltd",
  "4005": "Avance Logic Inc.",
  "4144": "Alpha Data",
  "416C": "Aladdin Knowledge Systems",
  "4348": "wch.cn",
  "4680": "UMAX Computer Corp.",
  "4843": "Hercules Computer Technology",
  "4943": "Growth Networks",
  "4954": "Integral Technologies",
  "4978": "Axil Computer Inc.",
  "4C48": "Lung Hwa Electronics",
  "4C53": "SBS-OR Industrial Computers",
  "4CA1": "Seanix Technology Inc",
  "4D51": "Mediaq Inc.",
  "4D54": "Microtechnica Co Ltd",
  "4DDC": "ILC Data Device Corp.",
  "04E8": "Samsung Windows Portable Devices",
  "5053": "TBS/Voyetra Technologies",
  "508A": "Samsung T10 MP3 Player",
  "5136": "S S Technologies",
  "5143": "Qualcomm Inc. USA",
  "5333": "S3 Graphics Co., Ltd",
  "544C": "Teralogic Inc",
  "5555": "Genroco Inc.",
  "5853": "Citrix Systems, Inc.",
  "6409": "Logitec Corp.",
  "6666": "Decision Computer International Co.",
  "6945": "ASMedia Technology Inc.",
  "7604": "O.N. Electric Co. Ltd.",
  "7D10": "D-Link Corporation",
  "8080": "Xirlink, Inc",
  "8086": "Intel Corporation",
  "8087": "Intel",
  "80EE": "Oracle Corporation - InnoTek Systemberatung GmbH",
  "8866": "T-Square Design Inc.",
  "8888": "Silicon Magic",
  "8E0E": "Computone Corporation",
  "9004": "Adaptec Inc",
  "9005": "Adaptec Inc",
  "919A": "Gigapixel Corp",
  "9412": "Holtek",
  "9699": "Omni Media Technology Inc.",
  "9710": "MosChip Semiconductor Technology",
  "9902": "StarGen, Inc.",
  "A0A0": "Aopen Inc.",
  "A0F1": "Unisys Corporation",
  "A200": "NEC Corp.",
  "A259": "Hewlett Packard",
  "A304": "Sony",
  "A727": "3com Corporation",
  "AA42": "Abekas, Inc",
  "AC1E": "Digital Receiver Technology Inc",
  "B1B3": "Shiva Europe Ltd.",
  "B894": "Brown & Sharpe Mfg. Co.",
  "BEEF": "Mindstream Computing",
  "C001": "TSI Telsys",
  "C0A9": "Micron/Crucial Technology",
  "C0DE": "Motorola",
  "C0FE": "Motion Engineering Inc.",
  "C622": "Hudson Soft Co Ltd",
  "CA50": "Varian, Inc",
  "CAFE": "Chrysalis-ITS",
  "CCCC": "Catapult Communications",
  "D4D4": "Curtiss-Wright Controls Embedded Computing",
  "DC93": "Dawicontrol",
  "DEAD": "Indigita Corporation",
  "DEAF": "Middle Digital, Inc",
  "E159": "Tiger Jet Network Inc",
  "E4BF": "EKF Elektronik GMBH",
  "EA01": "Eagle Technology",
  "EABB": "Aashima Technology B.V.",
  "EACE": "Endace Measurement Systems Ltd.",
  "ECC0": "Echo Digital Audio Corporation",
  "EDD8": "ARK Logic, Inc",
  "F5F5": "F5 Networks Inc.",
  "FA57": "Interagon AS"
}

module.exports = vendors;
